### ISSUE TITLE
SSL not supported?

### ISSUE THREAD

**Issue by pathwayx99** [ArtemVladimirov/broadlinkac2mqtt#1]
Hi, thanks for this!

I'm trying to get this to work and I've tried both the docker and stand-alone app, but I fail to connect to my MQTT broker, a mosquitto instance running with SSL (on port 8883) and username/password required. The app logs:

```
DBG config/config.go:45 > Start reading a config file 
ERR app/main.go:156 > Failed to connect mqtt 
fatal app/main.go:260 > failed to get a new App | error=network Error : EOF
```

I didn't see an option in the config.yml to support SSL. Is that perhaps the issue?

**Comment by ArtemVladimirov** [comment]
Hi, unfortunately the current version doesn't support SSL, but it's a good idea for the next release. I will definitely add your suggestion !

**Comment by pathwayx99** [comment]
Super, let me know if you need help testing that, I'll be happy to give it a shot.

**Comment by ArtemVladimirov** [comment]
Okey) I will implemet it on these weekends

**Comment by ArtemVladimirov** [comment]
https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/tag/v1.0.0

**Comment by pathwayx99** [comment]
Have tested it, can confirm it's working fine in my setup (TLS w. login/password without certificates). Well done!
