### ISSUE TITLE
1.4.0 HAOS add-on doesn't start

### ISSUE THREAD

**Issue by oopiicaa** [ArtemVladimirov/broadlinkac2mqtt#25]
Hey,
I could update the add-on to 1.4.0 after your fix, but the latest version does not start. Here is the add-on log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/bin/ash: /broadlinkac2mqtt/broadlinkac2mqtt: not found
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by ArtemVladimirov** [comment]
What kind of device do you have? 
I have already met such an error myself, the problem is in cross-compilation, it seems that pre-prepared binary files do not run. It looks like we'll have to return the compilation on the user device

**Comment by ArtemVladimirov** [comment]
I returned the old method of compilation. 
Now you will need to delete the current module and repository to clear the cache. After that , re - add the repository and install the module .
https://github.com/ArtemVladimirov/hassio-add-ons/commit/3b5ae2f9c894611fd155e74ba05ced9ad513c170

**Comment by oopiicaa** [comment]
Thanks, it's working again!

I have VOX IVA1-12IR A/C unit with Wi-Fi dongle (working with AC Freedom app).

Thanks again, for your swift help and this add-on.
