### ISSUE TITLE
Discovered MQTT entities with a name that is equal to the device name

### ISSUE THREAD

**Issue by llozanos81** [ArtemVladimirov/broadlinkac2mqtt#26]
@ArtemVladimirov , thanks for this awesome solution, today we are facing this issue:

Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

This stops working in version 2024.2.0. Please address before upgrading.

https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

**Comment by ArtemVladimirov** [comment]
https://github.com/ArtemVladimirov/broadlinkac2mqtt/pull/27

**Comment by ArtemVladimirov** [comment]
Fixed

https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/tag/v1.4.1
