### ISSUE TITLE
Error On Install

### ISSUE THREAD

**Issue by MattiaFontanaErrepinet** [ArtemVladimirov/broadlinkac2mqtt#33]
Hi i try to install this on my home assistant, home assistant is hosted to Esxi Server.

Show this error when i try to install 

` The command '/bin/ash -o pipefail -c if [ "${BUILD_ARCH}" = "armhf" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-arm.tar.gz; elif [ "${BUILD_ARCH}" = "armv7" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-arm7.tar.gz; elif [ "${BUILD_ARCH}" = "aarch64" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-arm64.tar.gz; elif [ "${BUILD_ARCH}" = "i386" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-386.tar.gz; elif [ "${BUILD_ARCH}" = "amd64" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-amd64.tar.gz; else echo 'NOT VALID BUILD'; exit 1; fi && tar -xzf broadlinkac2mqtt.tar.gz && rm broadlinkac2mqtt.tar.gz && chmod a+x ./run.sh && mkdir config && apk add --no-cache gcc g++ make && pip3 install --no-cache-dir -U pyyaml' returned a non-zero code: 1 `

**Comment by ArtemVladimirov** [comment]
Do you have Hassio on your Esxi Server?
You took a docker file from the hassio plugin repository, if you don't have hassio, then this docker file won't work.
