### ISSUE TITLE
Unable to build container on Raspberry 4 - docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

### ISSUE THREAD

**Issue by thelastoth** [ArtemVladimirov/broadlinkac2mqtt#35]
I'm unable to download, build and use the addon, I got the following error: docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

Sorry, maybe this is a lame issue, I'd appreciate every suggestion. 

Thanks!

**Comment by ArtemVladimirov** [comment]
Please try version 1.5.4
