### ISSUE TITLE
Change, define or convert temperature_unit 

### ISSUE THREAD

**Issue by ronluna** [ArtemVladimirov/broadlinkac2mqtt#36]
Is there a way to define change or convert the temperature unit from Celsius to Fahrenheit?

**Comment by ArtemVladimirov** [comment]
devices:
      - ip: 192.168.1.18
        mac: 34ea346b0mks   # Only this format is supported
        name: Bedroom AC
        port: 80 
        # Temperature Unit defines the temperature unit of the device, C or F.
        # If this is not set, the temperature unit is Celsius.
        temperature_unit: C

**Comment by ronluna** [comment]
This how is currently setup on my end:

`
- ip: 10.4.1.178
mac: 24dfa7eb8acd
name: Hall AC
port: 80
temperature_unit: F

`

but the temperature remains in Celsius .

**Comment by ArtemVladimirov** [comment]
What is your version? Please use 1.5.1

**Comment by ronluna** [comment]
I'm on version v1.4.1 as it is the one available on your git for the HassOS addons. possible to share how to get the addon to 1.5.1 correctly?

**Comment by ArtemVladimirov** [comment]
1.5.1 was with mistake. Actual version is 1.5.5

**Comment by ArtemVladimirov** [comment]
> I'm on version v1.4.1 as it is the one available on your git for the HassOS addons. possible to share how to get the addon to 1.5.1 correctly?

It should show a new version automatically
