### ISSUE TITLE
Install on aarch64

### ISSUE THREAD

**Issue by marcoahp** [ArtemVladimirov/broadlinkac2mqtt#5]
Hi Artem,
This is not an issue, I think that I don't know how can I install this addon in my home assistant.
How can I install in aarch64?  When I try to create a stack in portainer with your compose command I get: Deployment error
failed to deploy a stack: broadlinkac2mqtt Pulling no matching manifest for linux/arm64/v8 in the manifest list entries

and running docker command in my linux i get: 
Docker: "no matching manifest for linux/arm64/v8 in the manifest list entries"

Could you make an addon repository to install addon  easily like https://github.com/Arbuzov/hass-broadlink-ac-mqtt ?
Thanks mate

**Comment by marcoahp** [comment]
Thanks Artem

**Comment by oopiicaa** [comment]
> I will try to create the addon.

Hey Artem. I've just noticed some changes in your repo, so I went ahead and installed the add-on and it works great! Thank you so much!

**Comment by ArtemVladimirov** [comment]
I create the add on. Please, check
https://github.com/ArtemVladimirov/hassio-add-ons

**Comment by marcoahp** [comment]
ok I will check. Thanks

**Comment by marcoahp** [comment]
I've tested, but first I get an install error, but the addon is installed. After setting all and run, I get this error:


{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}
{"level":"error","input":{"Command":106,"Payload":"FLucRpm5EV2o+VxYVGBZjg==","Mac":"a043b08dfea3"},"time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:344","message":"Checksum is incorrect"}
{"level":"error","error":"ErrorInvalidResultPacket","device":"a043b08dfea3","time":"2023-07-19T09:49:56Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1142","message":"Failed to get AC States"}

**Comment by ArtemVladimirov** [comment]
Have you encountered this problem in a similar [project](https://github.com/liaan/broadlink_ac_mqtt)? 
If not, then it looks like I'll have to check the checksum verification function.
