### ISSUE TITLE
Not working if aircondition are on a different subnet

### ISSUE THREAD

**Issue by phanosp** [ArtemVladimirov/broadlinkac2mqtt#55]
Hi it works great but if the ac units are moved to a different subnet (other VLAN) and although I can ping the ACs from home assistant the plugin does not connect to any AC. 

Is there a limitation if the ACs are on a different VLAN?

**Comment by ArtemVladimirov** [comment]
Hi, there is no any limitation

**Comment by phanosp** [comment]
I see but why is not working? I see is using port 80 but is it tcp or udp? Does it using broadcast because I am trying to access it from another VLAN?
