### ISSUE TITLE
Allow ambient temperature measure over 32

### ISSUE THREAD

**Issue by earvingad** [ArtemVladimirov/broadlinkac2mqtt#9]
Hello,
I have noticed that the program limits the ambient reading temperature to 32.

For HA integration, using the temperature sensor of the AC is useful to avoid buying a separate one.

Ive tried to integrate [this code](https://github.com/liaan/broadlink_ac_mqtt/issues/87). However, sometimes the reads of the temperature jumps over 100 °C, Could it be integrated somehow? I am testing different values.

**Comment by ArtemVladimirov** [comment]
Thank you! I will test it!

**Comment by ArtemVladimirov** [comment]
Please, test it

**Comment by ArtemVladimirov** [comment]
v1.3.1

**Comment by earvingad** [comment]
v1.3.0 was behaving strangely, once temperature was above 30 (e.g. 31.8) it would report on 1.8. Currently testing v1.3.1, waiting for temperature to rise.

**Comment by earvingad** [comment]
I can confirm it's working nicely. Thanks for the update. 
![Screenshot_20230713-141747_Home_Assistant~3 1](https://github.com/ArtemVladimirov/broadlinkac2mqtt/assets/22012998/cb48b424-7db4-40d6-bf4c-251ad0ac2cfb)


![Screenshot_20230713-142016_Home_Assistant~2 1](https://github.com/ArtemVladimirov/broadlinkac2mqtt/assets/22012998/006b989a-60d4-4cb5-ba5f-9dd0b53b606d)
